# Generated by Django 4.0.4 on 2022-05-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_mobile_alter_customer_phone'),
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='customer.customer'),
        ),
    ]
