# Generated by Django 4.0.4 on 2022-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220520_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_event'),
        ),
    ]
