# Generated by Django 4.0.4 on 2022-05-14 14:27

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220501_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, validators=[authentication.models.manager_validator], verbose_name='manager'),
        ),
    ]
