# Generated by Django 4.0.4 on 2022-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220501_1143'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('manager_id', 1)), name='is_able_to_be_manager'),
        ),
    ]
